#!/bin/sh

PARANUM="$#"
PROGRAM=${0##*/}
LOCAL_PATH=${0%/*}
ROOTDIR=$(dirname $(dirname $(readlink -f $0)))
BOARD=$1
if [ $# != 1 ] ; then 
BOARD=kylin
fi



echo "Waiting for ${BOARD} board enter fastboot mode..." 
while ! sudo lsusb -d 2207: ; do sleep .5; done
echo "Flashing U-boot for ${BOARD} board!"
${ROOTDIR}/rkflashtool/rkflashloader
echo "Done!"
sleep 2
echo "Rebooting ${BOARD} board!"
sudo ${ROOTDIR}/rkflashtool/rkflashtool b
sleep 1
echo "Done!"
echo "Waiting for ${BOARD} board enter fastboot mode..."
while ! sudo lsusb -d 2207: ; do sleep .5; done
echo "Flashing kernel image for ${BOARD} board!"
sudo fastboot -i 0x2207 flash boot_a ${ROOTDIR}/image/${BOARD}-kernel.img
echo "Done!"
sleep 1
echo "Flashing rootfs image for ${BOARD} board!"
sudo fastboot -i 0x2207 flash system_a ${ROOTDIR}/image/${BOARD}-rootfs.img
echo "Done!"
echo "Rebooting ${BOARD} board!"
sleep 1
sudo fastboot -i 0x2207 reboot
echo "Done!"
